### ISSUE TITLE
Unable to determine the serialization information for the expression

### ISSUE THREAD

**Issue by zhujinhu21** [RobThree/MongoRepository#27] opened 2016-02-26 11:18 UTC
Unable to determine the serialization information for the expression: Enumerable.Select<News, String>(m.MsgBody.news, (News s) => s.title).

I user mongocsharpdriver 1.10.1 .mongodb 3.0 server.
my search code is
 var msgList2 = messageRepository.Where(m => m.MsgBody.news.Select(s => s.title).Contains(keyword)).ToList();

collection structure is 
![26578-20160225224407411-1394691890](https://cloud.githubusercontent.com/assets/4327149/13350877/dc73137a-dcbd-11e5-8af4-91fe295a5fd9.png)

data model is

![qq 20160226191302](https://cloud.githubusercontent.com/assets/4327149/13350906/0ea17af8-dcbe-11e5-824c-848ed7acf6d5.png)

What is the problem? Thanks.

**Comment by RobThree** [comment] 2016-02-26 12:43
The problem is that the [mongo-csharp-driver](https://github.com/mongodb/mongo-csharp-driver) can't convert your expression to a MongoDb query. I would try to reproduce and maybe figure out if there's an easy workaround / fix for this but I can't copy/paste code from screenshots and I'm lazy :wink:

**Comment by RobThree** [comment] 2016-02-26 13:00
As said; I don't have enough code in the above screenshots to reproduce but something like this should work:

```
var msgList2 = repo.Where(m => m.news.Any(n => n.title.Contains("foo"))).ToList();
```

Here's a simple sample I used to (try to) reproduce your problem as best I could: [TMDB.zip](https://github.com/RobThree/MongoRepository/files/148209/TMDB.zip)

**Comment by zhujinhu21** [comment] 2016-02-27 03:37
``
thanks
AddressBookMessage store in mongo,and it's property  MsgBody  is class.
[code.zip](https://github.com/RobThree/MongoRepository/files/149197/code.zip)

**Comment by zhujinhu21** [comment] 2016-02-27 03:40
public IHttpActionResult Search(string keyword)
 {
MongoRepository<AddressBookMessage> messageRepository = new MongoRepository<AddressBookMessage>();

var msgList = messageRepository.Where(m => m.MsgBody.news.Select(s => s.title).Contains(keyword)).ToList();
return Ok(msgList );
}

**Comment by zhujinhu21** [comment] 2016-02-27 09:37
I use you code var msgList2 = repo.Where(m => m.news.Any(n => n.title.Contains("foo"))).ToList();
and it woks.thank you

**Comment by RobThree** [comment] 2016-02-27 11:43
You're welcome.

**Closed by RobThree** 2016-02-27 11:43 UTC
